spring:
  cloud:
    gateway:
      routes:
      - id: hello_route
        uri: forward:/greet
        predicates:
        - Path=/api/hello
        - Method=GET
        filters:
        - OperationType
